# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfba0b1de1a9c004ab3fcb6e7b4c694287e6161081b4f83c030a32d3e96f2d2c915e1b359a46154453a44077ebc0c15a3f01b0978729dbc275b531041933f043

test:
  secret_key_base: 545f863bb563356ceff655c16d140ac14ed716f8bfc2be07185c52f744666004b7e05e3447ab94bb649658285ea9085291dc03ce1f700afdc4dadaf7bd838c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
